CDPD-45238: HIVE-26511: Fix NoClassDefFoundError in HMS for HBaseConfiguration. (#3569). (Ayush Saxena, reviewed by Zhihua Deng and Istvan Toth)
(cherry picked from commit 976102a4a0216d1c027ab5155f0a25b5f00fdcf8)
Change-Id: I62f0cd7a9008fc9aa4da187ce5a730f7647af7bb